<?php
declare(strict_types=1);
if(!isset($mysqli)) require __DIR__ . '/../../../config.php';
require_once __DIR__ . '/../../../includes/setup_services_service.php';
$defaults=['service_type'=>'','from_locaion'=>'','to_locaion'=>'','service_name_english'=>'','service_name_arabic'=>'','service_categories'=>'Private','vehicle_type'=>'','buying_price'=>'','selling_price'=>'','sic_adult_price'=>'','sic_children_price'=>''];$form=$defaults;$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){if(!setup_services_csrf_validate((string)($_POST['_token']??''))){$errors[]='Invalid request token.';}else{foreach($defaults as $k=>$_)$form[$k]=trim((string)($_POST[$k]??''));$r=setup_services_create($mysqli,$form);if(!empty($r['ok'])){setup_services_flash_set('success','Service created successfully.');header('Location: index.php?page=setup_service_view&id='.(int)($r['id']??0));exit;}$errors=$r['errors']??['Create failed.'];}}
$types=setup_services_types($mysqli);$vehicleTypes=setup_services_vehicle_types($mysqli);$locations=setup_services_locations($mysqli);$csrf=setup_services_csrf_token();require __DIR__ . '/../../../includes/header.php';require __DIR__ . '/../../../includes/nav.php';
?>
<div class="flex gap-6 w-full"><aside class="hidden lg:block w-72 shrink-0"><?php require __DIR__ . '/../sidebar.php'; ?></aside><main class="flex-1 px-4"><div class="space-y-4">
<?php $breadcrumbParentLabel='Service Setup';$breadcrumbParentHref='index.php?page=setup_services';$breadcrumbCurrent='Create Service';require __DIR__ . '/../../../includes/breadcrumb.php'; ?>
<div class="flex flex-wrap gap-2"><a href="index.php?page=setup_services" class="btn btn-sm btn-outline">Back to service list</a></div>
<div class="card bg-base-100 shadow-xl border border-base-300"><div class="card-body space-y-4"><?php if($errors): ?><div class="alert alert-error"><span><?= h(implode(' ',$errors)) ?></span></div><?php endif; ?>
<form method="post" action="index.php?page=setup_service_create" class="space-y-3"><input type="hidden" name="_token" value="<?= h($csrf) ?>">
<div class="max-w-5xl mx-auto border border-base-300 rounded-box overflow-hidden"><div class="px-4 py-2.5 bg-linear-to-r from-sky-700 to-cyan-600 text-white font-bold text-base">Create Service</div><div class="divide-y divide-base-300">
<?php $rowClass='grid grid-cols-1 md:grid-cols-[190px_1fr] items-center gap-2 px-3 py-1.5'; $labelClass='font-semibold text-sm text-base-content/80'; $inputClass='input input-bordered input-sm text-sm w-full max-w-xl'; $selectClass='select select-bordered select-sm text-sm w-full max-w-xs'; ?>
<div class="<?= $rowClass ?>"><label class="<?= $labelClass ?>">Service Type :</label><select name="service_type" class="<?= $selectClass ?>" required><option value="">Select Service Type</option><?php foreach($types as $t): ?><option value="<?= h($t) ?>" <?= $form['service_type']===$t?'selected':'' ?>><?= h($t) ?></option><?php endforeach; ?></select></div>
<div class="<?= $rowClass ?>"><label class="<?= $labelClass ?>">From Location :</label><select name="from_locaion" class="<?= $selectClass ?>" required><option value="">Select Location</option><?php foreach($locations as $l): ?><option value="<?= h((string)$l['location_name']) ?>" <?= $form['from_locaion']===(string)$l['location_name']?'selected':'' ?>><?= h((string)$l['location_name']) ?></option><?php endforeach; ?></select></div>
<div class="<?= $rowClass ?>"><label class="<?= $labelClass ?>">To Location :</label><select name="to_locaion" class="<?= $selectClass ?>" required><option value="">Select Location</option><?php foreach($locations as $l): ?><option value="<?= h((string)$l['location_name']) ?>" <?= $form['to_locaion']===(string)$l['location_name']?'selected':'' ?>><?= h((string)$l['location_name']) ?></option><?php endforeach; ?></select></div>
<div class="<?= $rowClass ?>"><label class="<?= $labelClass ?>">Service Name Eng :</label><input name="service_name_english" value="<?= h($form['service_name_english']) ?>" class="<?= $inputClass ?>" required></div>
<div class="<?= $rowClass ?>"><label class="<?= $labelClass ?>">Service Name Arb :</label><input name="service_name_arabic" value="<?= h($form['service_name_arabic']) ?>" class="<?= $inputClass ?>" required></div>
<div class="<?= $rowClass ?>"><label class="<?= $labelClass ?>">Service Categories :</label><select name="service_categories" id="service-categories" class="<?= $selectClass ?>" required><option value="Private" <?= $form['service_categories']==='Private'?'selected':'' ?>>Private</option><option value="SIC" <?= $form['service_categories']==='SIC'?'selected':'' ?>>SIC</option></select></div>
<div class="<?= $rowClass ?>"><label class="<?= $labelClass ?>">Vehicle Type :</label><select name="vehicle_type" class="<?= $selectClass ?>" required><option value="">Select Vehicle Type</option><?php foreach($vehicleTypes as $v): ?><option value="<?= h($v) ?>" <?= $form['vehicle_type']===$v?'selected':'' ?>><?= h($v) ?></option><?php endforeach; ?></select></div>
<div id="private-prices"><div class="<?= $rowClass ?>"><label class="<?= $labelClass ?>">Buying Price :</label><input name="buying_price" value="<?= h($form['buying_price']) ?>" class="<?= $inputClass ?>"></div><div class="<?= $rowClass ?>"><label class="<?= $labelClass ?>">Selling Price :</label><input name="selling_price" value="<?= h($form['selling_price']) ?>" class="<?= $inputClass ?>"></div></div>
<div id="sic-prices"><div class="<?= $rowClass ?>"><label class="<?= $labelClass ?>">SIC Adult Price :</label><input name="sic_adult_price" value="<?= h($form['sic_adult_price']) ?>" class="<?= $inputClass ?>"></div><div class="<?= $rowClass ?>"><label class="<?= $labelClass ?>">SIC Children Price :</label><input name="sic_children_price" value="<?= h($form['sic_children_price']) ?>" class="<?= $inputClass ?>"></div></div>
</div></div><div class="flex justify-center"><button class="btn btn-primary" type="submit">Submit</button></div></form></div></div>
</div></main></div>
<script>(function(){var c=document.getElementById('service-categories'),p=document.getElementById('private-prices'),s=document.getElementById('sic-prices');if(!c||!p||!s)return;function sync(){var v=c.value||'Private';p.style.display=v==='Private'?'block':'none';s.style.display=v==='SIC'?'block':'none';}c.addEventListener('change',sync);sync();})();</script>
<?php require __DIR__ . '/../../../includes/footer.php'; ?>
