<?php
declare(strict_types=1);
if(!isset($mysqli)) require __DIR__ . '/../../../config.php';
require_once __DIR__ . '/../../../includes/setup_services_service.php';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='delete_service'){ $t=(string)($_POST['_token']??'');$id=(int)($_POST['service_id']??0); if(!setup_services_csrf_validate($t))setup_services_flash_set('error','Invalid request token.'); elseif($id<=0)setup_services_flash_set('error','Invalid service.'); elseif(setup_services_delete($mysqli,$id))setup_services_flash_set('success','Service deleted successfully.'); else setup_services_flash_set('error','Delete failed.'); header('Location: index.php?page=setup_services'); exit; }
$fCountry=isset($_GET['f_country'])?trim((string)$_GET['f_country']):'';$fCity=isset($_GET['f_city'])?trim((string)$_GET['f_city']):'';$fType=isset($_GET['f_type'])?trim((string)$_GET['f_type']):'';
$rows=setup_services_list($mysqli,$fCountry!==''?$fCountry:null,$fCity!==''?$fCity:null,$fType!==''?$fType:null);
$countries=setup_services_countries($mysqli);$citiesAll=setup_services_cities_all($mysqli);$types=setup_services_types($mysqli);$flash=setup_services_flash_get();$csrf=setup_services_csrf_token();
require __DIR__ . '/../../../includes/header.php';require __DIR__ . '/../../../includes/nav.php';
?>
<div class="flex gap-6 w-full"><aside class="hidden lg:block w-72 shrink-0"><?php require __DIR__ . '/../sidebar.php'; ?></aside><main class="flex-1 px-4"><div class="space-y-4">
<?php $breadcrumbParentLabel='Setup';$breadcrumbParentHref='index.php?page=setup';$breadcrumbCurrent='Service Setup';require __DIR__ . '/../../../includes/breadcrumb.php'; ?>
<div class="card bg-base-100 shadow-xl border border-base-300"><div class="card-body space-y-4">
<?php if(!empty($flash)): ?><div class="alert <?= $flash['type']==='success'?'alert-success':'alert-error' ?>"><span><?= h((string)$flash['message']) ?></span></div><?php endif; ?>
<div class="max-w-5xl mx-auto border border-base-300 rounded-box overflow-hidden"><div class="px-4 py-2.5 bg-linear-to-r from-sky-700 to-cyan-600 text-white font-bold text-base">Service Setup</div>
<form method="get" action="index.php" class="p-4 space-y-3 border-b border-base-300 bg-base-100"><input type="hidden" name="page" value="setup_services"><div class="grid grid-cols-1 md:grid-cols-3 gap-3">
<label class="form-control w-full"><span class="label-text text-sm">Search country</span><select name="f_country" id="service-filter-country" class="select select-bordered select-sm w-full"><option value="">All</option><?php foreach($countries as $c): ?><option value="<?= h($c) ?>" <?= $fCountry===$c?'selected':'' ?>><?= h($c) ?></option><?php endforeach; ?></select></label>
<label class="form-control w-full"><span class="label-text text-sm">Select city</span><select name="f_city" id="service-filter-city" class="select select-bordered select-sm w-full"><option value="">All</option><?php foreach($citiesAll as $ct): ?><option value="<?= h($ct['city_name']) ?>" data-country="<?= h($ct['city_country_name']) ?>" <?= $fCity===$ct['city_name']?'selected':'' ?>><?= h($ct['city_name']) ?></option><?php endforeach; ?></select></label>
<label class="form-control w-full"><span class="label-text text-sm">Select type</span><select name="f_type" class="select select-bordered select-sm w-full"><option value="">All</option><?php foreach($types as $t): ?><option value="<?= h($t) ?>" <?= $fType===$t?'selected':'' ?>><?= h($t) ?></option><?php endforeach; ?></select></label>
</div><div class="flex flex-wrap gap-2"><button type="submit" class="btn btn-primary btn-sm">Search</button><a href="index.php?page=setup_services" class="btn btn-ghost btn-sm">Reset</a></div></form></div>
<div class="flex justify-center"><a href="index.php?page=setup_service_create" class="btn btn-success btn-sm">Create Service</a></div>
<div class="overflow-x-auto rounded-box border border-base-300"><table class="table table-zebra table-sm"><thead><tr><th>S.N</th><th>Service Type</th><th>Service Name Eng</th><th>Service Name Arb</th><th>Vehicle Type</th><th>Buying Price</th><th>Selling Price</th><th>View</th><th>Edit</th><th>Delete</th></tr></thead><tbody>
<?php $sn=1; foreach($rows as $row): ?><tr><td><?= $sn++ ?></td><td><?= h((string)$row['service_type']) ?></td><td class="max-w-xs whitespace-normal"><?= h((string)$row['service_name_english']) ?></td><td class="max-w-xs whitespace-normal text-right" dir="rtl" lang="ar"><?= h(normalize_arabic_text((string)$row['service_name_arabic'])) ?></td><td><?= h((string)$row['vehicle_type']) ?></td><td><?= h((string)$row['buying_price']) ?></td><td><?= h((string)$row['selling_price']) ?></td><td><a class="btn btn-xs btn-info btn-outline" href="index.php?page=setup_service_view&id=<?= (int)$row['service_id'] ?>">View</a></td><td><a class="btn btn-xs btn-outline" href="index.php?page=setup_service_edit&id=<?= (int)$row['service_id'] ?>">Edit</a></td><td><button type="button" class="btn btn-xs btn-error btn-outline js-delete-service" data-id="<?= (int)$row['service_id'] ?>" data-name="<?= h((string)$row['service_name_english']) ?>">Delete</button></td></tr><?php endforeach; ?>
</tbody></table></div></div></div>
</div></main></div>
<form id="delete-service-form" method="post" action="index.php?page=setup_services" class="hidden"><input type="hidden" name="_token" value="<?= h($csrf) ?>"><input type="hidden" name="action" value="delete_service"><input type="hidden" name="service_id" id="delete-service-id"></form>
<dialog id="delete-service-modal" class="agent-delete-dialog"><div class="agent-delete-dialog__surface"><h3 class="font-bold text-lg mb-1">Delete service?</h3><p class="agent-delete-dialog__message" id="delete-service-msg">Are you sure? This cannot be undone.</p><div class="agent-delete-dialog__actions"><button type="button" class="btn btn-outline" id="delete-service-no">No</button><button type="button" class="btn btn-error" id="delete-service-yes">Yes</button></div></div></dialog>
<script>(function(){var co=document.getElementById('service-filter-country'),ci=document.getElementById('service-filter-city');if(co&&ci){function sync(){var c=co.value||'';Array.prototype.forEach.call(ci.options,function(opt,i){if(i===0)return;opt.hidden=c!==''&&(opt.getAttribute('data-country')||'')!==c;});var s=ci.options[ci.selectedIndex];if(s&&s.hidden)ci.value='';}co.addEventListener('change',sync);sync();}var m=document.getElementById('delete-service-modal'),f=document.getElementById('delete-service-form'),i=document.getElementById('delete-service-id'),msg=document.getElementById('delete-service-msg'),n=document.getElementById('delete-service-no'),y=document.getElementById('delete-service-yes');if(!m||!f||!i||!msg||!n||!y)return;document.querySelectorAll('.js-delete-service').forEach(function(b){b.addEventListener('click',function(){i.value=this.getAttribute('data-id')||'';var name=this.getAttribute('data-name')||'';msg.textContent=name?'Are you sure you want to delete service "'+name+'"? This cannot be undone.':'Are you sure you want to delete this service? This cannot be undone.';m.showModal();});});n.addEventListener('click',function(){m.close();});y.addEventListener('click',function(){m.close();f.submit();});})();</script>
<?php require __DIR__ . '/../../../includes/footer.php'; ?>
