<?php
declare(strict_types=1);
if(!isset($mysqli)) require __DIR__ . '/../../../config.php';
require_once __DIR__ . '/../../../includes/setup_locations_service.php';
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='delete_location'){ $t=(string)($_POST['_token']??'');$id=(int)($_POST['location_id']??0); if(!setup_locations_csrf_validate($t)) setup_locations_flash_set('error','Invalid request token.'); elseif($id<=0) setup_locations_flash_set('error','Invalid location.'); elseif(setup_locations_delete($mysqli,$id)) setup_locations_flash_set('success','Location deleted successfully.'); else setup_locations_flash_set('error','Delete failed.'); header('Location: index.php?page=setup_locations'); exit; }
$rows=setup_locations_list($mysqli);$flash=setup_locations_flash_get();$csrf=setup_locations_csrf_token();
require __DIR__ . '/../../../includes/header.php';require __DIR__ . '/../../../includes/nav.php';
?>
<div class="flex gap-6 w-full"><aside class="hidden lg:block w-72 shrink-0"><?php require __DIR__ . '/../sidebar.php'; ?></aside><main class="flex-1 px-4"><div class="space-y-4">
<?php $breadcrumbParentLabel='Setup';$breadcrumbParentHref='index.php?page=setup';$breadcrumbCurrent='Location Setup';require __DIR__ . '/../../../includes/breadcrumb.php'; ?>
<div class="card bg-base-100 shadow-xl border border-base-300"><div class="card-body space-y-4">
<?php if(!empty($flash)): ?><div class="alert <?= $flash['type']==='success'?'alert-success':'alert-error' ?>"><span><?= h((string)$flash['message']) ?></span></div><?php endif; ?>
<div class="flex justify-center"><a href="index.php?page=setup_location_create" class="btn btn-success btn-sm">Create Location</a></div>
<div class="overflow-x-auto rounded-box border border-base-300"><table class="table table-zebra table-sm"><thead><tr><th>S.N</th><th>Location Name Eng</th><th>Location Name Arb</th><th>Country</th><th>City</th><th>Edit</th><th>Delete</th></tr></thead><tbody>
<?php $sn=1; foreach($rows as $row): $arb = (string) $row['location_name_arb']; if (function_exists('normalize_arabic_text')) { $arb = normalize_arabic_text($arb); } ?><tr><td><?= $sn++ ?></td><td class="font-medium"><a class="link link-hover" href="index.php?page=setup_location_view&id=<?= (int)$row['location_id'] ?>"><?= h((string)$row['location_name']) ?></a></td><td class="max-w-xs whitespace-normal text-right" dir="rtl" lang="ar"><?= h($arb) ?></td><td><?= h((string)$row['location_country']) ?></td><td><?= h((string)$row['location_city']) ?></td><td><a class="btn btn-xs btn-outline" href="index.php?page=setup_location_edit&id=<?= (int)$row['location_id'] ?>">Edit</a></td><td><button type="button" class="btn btn-xs btn-error btn-outline js-delete-location" data-id="<?= (int)$row['location_id'] ?>" data-name="<?= h((string)$row['location_name']) ?>">Delete</button></td></tr><?php endforeach; ?>
</tbody></table></div></div></div>
</div></main></div>
<form id="delete-location-form" method="post" action="index.php?page=setup_locations" class="hidden"><input type="hidden" name="_token" value="<?= h($csrf) ?>"><input type="hidden" name="action" value="delete_location"><input type="hidden" name="location_id" id="delete-location-id"></form>
<dialog id="delete-location-modal" class="agent-delete-dialog"><div class="agent-delete-dialog__surface"><h3 class="font-bold text-lg mb-1">Delete location?</h3><p class="agent-delete-dialog__message" id="delete-location-msg">Are you sure? This cannot be undone.</p><div class="agent-delete-dialog__actions"><button type="button" class="btn btn-outline" id="delete-location-no">No</button><button type="button" class="btn btn-error" id="delete-location-yes">Yes</button></div></div></dialog>
<script>(function(){var m=document.getElementById('delete-location-modal'),f=document.getElementById('delete-location-form'),i=document.getElementById('delete-location-id'),msg=document.getElementById('delete-location-msg'),n=document.getElementById('delete-location-no'),y=document.getElementById('delete-location-yes');if(!m||!f||!i||!msg||!n||!y)return;document.querySelectorAll('.js-delete-location').forEach(function(b){b.addEventListener('click',function(){i.value=this.getAttribute('data-id')||'';var name=this.getAttribute('data-name')||'';msg.textContent=name?'Are you sure you want to delete location "'+name+'"? This cannot be undone.':'Are you sure you want to delete this location? This cannot be undone.';m.showModal();});});n.addEventListener('click',function(){m.close();});y.addEventListener('click',function(){m.close();f.submit();});})();</script>
<?php require __DIR__ . '/../../../includes/footer.php'; ?>
