<?php
declare(strict_types=1);

function setup_drivers_flash_set(string $type, string $message): void { $_SESSION['setup_drivers_flash'] = ['type' => $type, 'message' => $message]; }
function setup_drivers_flash_get(): ?array { if (!isset($_SESSION['setup_drivers_flash'])) return null; $f = $_SESSION['setup_drivers_flash']; unset($_SESSION['setup_drivers_flash']); return is_array($f) ? $f : null; }
function setup_drivers_csrf_token(): string { if (empty($_SESSION['setup_drivers_csrf'])) $_SESSION['setup_drivers_csrf'] = bin2hex(random_bytes(16)); return (string) $_SESSION['setup_drivers_csrf']; }
function setup_drivers_csrf_validate(string $token): bool { $s = (string) ($_SESSION['setup_drivers_csrf'] ?? ''); return $s !== '' && hash_equals($s, $token); }
function setup_drivers_next_id(mysqli $mysqli): int { $r = $mysqli->query('SELECT COALESCE(MAX(driver_id),0)+1 AS n FROM driver'); if ($r && ($row = $r->fetch_assoc())) return max(1, (int) ($row['n'] ?? 1)); return 1; }
function setup_drivers_list(mysqli $mysqli): array { $r = $mysqli->query('SELECT driver_id, driver_name, Username, driver_contact_no, driver_address, driver_email FROM driver ORDER BY driver_name'); $rows = []; if ($r) while ($row = $r->fetch_assoc()) $rows[] = $row; return $rows; }
function setup_drivers_find(mysqli $mysqli, int $id): ?array { $s = $mysqli->prepare('SELECT driver_id, driver_name, Username, driver_contact_no, driver_address, driver_email FROM driver WHERE driver_id = ? LIMIT 1'); if (!$s) return null; $s->bind_param('i', $id); $s->execute(); $row = $s->get_result()->fetch_assoc(); $s->close(); return $row ?: null; }
function setup_drivers_validate(array $d, bool $isCreate): array { $e = []; if (mb_strlen(trim((string) ($d['driver_name'] ?? ''))) < 2) $e[] = 'Driver name is required.'; if (mb_strlen(trim((string) ($d['driver_contact_no'] ?? ''))) < 2) $e[] = 'Contact number is required.'; if (mb_strlen(trim((string) ($d['driver_address'] ?? ''))) < 2) $e[] = 'Address is required.'; if ($isCreate && mb_strlen(trim((string) ($d['Username'] ?? ''))) < 2) $e[] = 'Username is required.'; if ($isCreate && mb_strlen(trim((string) ($d['password'] ?? ''))) < 2) $e[] = 'Password is required.'; if ($isCreate && ($d['password'] ?? '') !== ($d['con_password'] ?? '')) $e[] = 'Confirm password does not match.'; return $e; }
function setup_drivers_username_exists(mysqli $mysqli, string $username, int $excludeDriverId = 0): bool { $sql = 'SELECT driver_id FROM driver WHERE Username = ?'; if ($excludeDriverId > 0) $sql .= ' AND driver_id <> ?'; $sql .= ' LIMIT 1'; $s = $mysqli->prepare($sql); if (!$s) return false; if ($excludeDriverId > 0) $s->bind_param('si', $username, $excludeDriverId); else $s->bind_param('s', $username); $s->execute(); $exists = (bool) $s->get_result()->fetch_assoc(); $s->close(); return $exists; }
function setup_drivers_create(mysqli $mysqli, array $input): array { $d = ['driver_name' => trim((string) ($input['driver_name'] ?? '')), 'driver_contact_no' => trim((string) ($input['driver_contact_no'] ?? '')), 'driver_address' => trim((string) ($input['driver_address'] ?? '')), 'driver_email' => trim((string) ($input['driver_email'] ?? '')), 'Username' => trim((string) ($input['Username'] ?? '')), 'password' => trim((string) ($input['password'] ?? '')), 'con_password' => trim((string) ($input['con_password'] ?? ''))]; $e = setup_drivers_validate($d, true); if ($e) return ['ok' => false, 'errors' => $e]; if (setup_drivers_username_exists($mysqli, $d['Username'])) return ['ok' => false, 'errors' => ['Username already exists.']]; $id = setup_drivers_next_id($mysqli); $passwordHash = md5($d['password']); $s = $mysqli->prepare('INSERT INTO driver (driver_id, driver_name, driver_contact_no, driver_address, driver_email, Username, password) VALUES (?, ?, ?, ?, ?, ?, ?)'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare insert.']]; $s->bind_param('issssss', $id, $d['driver_name'], $d['driver_contact_no'], $d['driver_address'], $d['driver_email'], $d['Username'], $passwordHash); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true, 'id' => $id] : ['ok' => false, 'errors' => ['Failed to create driver.']]; }
function setup_drivers_update(mysqli $mysqli, int $id, array $input): array { $d = ['driver_name' => trim((string) ($input['driver_name'] ?? '')), 'driver_contact_no' => trim((string) ($input['driver_contact_no'] ?? '')), 'driver_address' => trim((string) ($input['driver_address'] ?? '')), 'driver_email' => trim((string) ($input['driver_email'] ?? ''))]; $e = setup_drivers_validate($d, false); if ($e) return ['ok' => false, 'errors' => $e]; $s = $mysqli->prepare('UPDATE driver SET driver_name = ?, driver_contact_no = ?, driver_address = ?, driver_email = ? WHERE driver_id = ?'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare update.']]; $s->bind_param('ssssi', $d['driver_name'], $d['driver_contact_no'], $d['driver_address'], $d['driver_email'], $id); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true] : ['ok' => false, 'errors' => ['Failed to update driver.']]; }
function setup_drivers_update_password(mysqli $mysqli, int $id, string $password): array { if (mb_strlen(trim($password)) < 2) return ['ok' => false, 'errors' => ['Password is required.']]; $hash = md5($password); $s = $mysqli->prepare('UPDATE driver SET password = ? WHERE driver_id = ?'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare password update.']]; $s->bind_param('si', $hash, $id); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true] : ['ok' => false, 'errors' => ['Failed to update password.']]; }
function setup_drivers_delete(mysqli $mysqli, int $id): bool { $s = $mysqli->prepare('DELETE FROM driver WHERE driver_id = ?'); if (!$s) return false; $s->bind_param('i', $id); $ok = $s->execute(); $s->close(); return $ok; }

