<?php
declare(strict_types=1);

function setup_designations_flash_set(string $type, string $message): void { $_SESSION['setup_designations_flash'] = ['type' => $type, 'message' => $message]; }
function setup_designations_flash_get(): ?array { if (!isset($_SESSION['setup_designations_flash'])) return null; $f = $_SESSION['setup_designations_flash']; unset($_SESSION['setup_designations_flash']); return is_array($f) ? $f : null; }
function setup_designations_csrf_token(): string { if (empty($_SESSION['setup_designations_csrf'])) $_SESSION['setup_designations_csrf'] = bin2hex(random_bytes(16)); return (string) $_SESSION['setup_designations_csrf']; }
function setup_designations_csrf_validate(string $token): bool { $s = (string) ($_SESSION['setup_designations_csrf'] ?? ''); return $s !== '' && hash_equals($s, $token); }
function setup_designations_next_id(mysqli $mysqli): int { $r = $mysqli->query('SELECT COALESCE(MAX(position_id),0)+1 AS n FROM position'); if ($r && ($row = $r->fetch_assoc())) return max(1, (int) ($row['n'] ?? 1)); return 1; }
function setup_designations_list(mysqli $mysqli): array { $r = $mysqli->query('SELECT position_id, position_name, position_short_name FROM position ORDER BY position_name'); $rows = []; if ($r) while ($row = $r->fetch_assoc()) $rows[] = $row; return $rows; }
function setup_designations_find(mysqli $mysqli, int $id): ?array { $s = $mysqli->prepare('SELECT position_id, position_name, position_short_name FROM position WHERE position_id = ? LIMIT 1'); if (!$s) return null; $s->bind_param('i', $id); $s->execute(); $row = $s->get_result()->fetch_assoc(); $s->close(); return $row ?: null; }
function setup_designations_validate(array $d): array { $e = []; if (mb_strlen(trim((string) ($d['position_name'] ?? ''))) < 2) $e[] = 'Designation name is required.'; return $e; }
function setup_designations_name_exists(mysqli $mysqli, string $name, int $excludeId = 0): bool { $sql = 'SELECT position_id FROM position WHERE position_name = ?'; if ($excludeId > 0) $sql .= ' AND position_id <> ?'; $sql .= ' LIMIT 1'; $s = $mysqli->prepare($sql); if (!$s) return false; if ($excludeId > 0) $s->bind_param('si', $name, $excludeId); else $s->bind_param('s', $name); $s->execute(); $exists = (bool) $s->get_result()->fetch_assoc(); $s->close(); return $exists; }
function setup_designations_create(mysqli $mysqli, array $input): array { $d = ['position_name' => trim((string) ($input['position_name'] ?? '')), 'position_short_name' => trim((string) ($input['position_short_name'] ?? ''))]; $e = setup_designations_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; if (setup_designations_name_exists($mysqli, $d['position_name'])) return ['ok' => false, 'errors' => ['Designation already exists.']]; $id = setup_designations_next_id($mysqli); $s = $mysqli->prepare('INSERT INTO position (position_id, position_name, position_short_name) VALUES (?, ?, ?)'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare insert.']]; $s->bind_param('iss', $id, $d['position_name'], $d['position_short_name']); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true, 'id' => $id] : ['ok' => false, 'errors' => ['Failed to create designation.']]; }
function setup_designations_update(mysqli $mysqli, int $id, array $input): array { $d = ['position_name' => trim((string) ($input['position_name'] ?? '')), 'position_short_name' => trim((string) ($input['position_short_name'] ?? ''))]; $e = setup_designations_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; if (setup_designations_name_exists($mysqli, $d['position_name'], $id)) return ['ok' => false, 'errors' => ['Designation already exists.']]; $s = $mysqli->prepare('UPDATE position SET position_name = ?, position_short_name = ? WHERE position_id = ?'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare update.']]; $s->bind_param('ssi', $d['position_name'], $d['position_short_name'], $id); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true] : ['ok' => false, 'errors' => ['Failed to update designation.']]; }
function setup_designations_delete(mysqli $mysqli, int $id): bool { $s = $mysqli->prepare('DELETE FROM position WHERE position_id = ?'); if (!$s) return false; $s->bind_param('i', $id); $ok = $s->execute(); $s->close(); return $ok; }

