<?php
declare(strict_types=1);

function setup_vehicle_types_flash_set(string $type, string $message): void { $_SESSION['setup_vehicle_types_flash'] = ['type' => $type, 'message' => $message]; }
function setup_vehicle_types_flash_get(): ?array { if (!isset($_SESSION['setup_vehicle_types_flash'])) return null; $f = $_SESSION['setup_vehicle_types_flash']; unset($_SESSION['setup_vehicle_types_flash']); return is_array($f) ? $f : null; }
function setup_vehicle_types_csrf_token(): string { if (empty($_SESSION['setup_vehicle_types_csrf'])) $_SESSION['setup_vehicle_types_csrf'] = bin2hex(random_bytes(16)); return (string) $_SESSION['setup_vehicle_types_csrf']; }
function setup_vehicle_types_csrf_validate(string $token): bool { $s = (string) ($_SESSION['setup_vehicle_types_csrf'] ?? ''); return $s !== '' && hash_equals($s, $token); }
function setup_vehicle_types_next_id(mysqli $mysqli): int { $r = $mysqli->query('SELECT COALESCE(MAX(vehicle_type_id),0)+1 AS n FROM vehicle_type'); if ($r && ($row = $r->fetch_assoc())) return max(1, (int) ($row['n'] ?? 1)); return 1; }
function setup_vehicle_types_list(mysqli $mysqli): array { $r = $mysqli->query('SELECT vehicle_type_id, vehicle_type_name FROM vehicle_type ORDER BY vehicle_type_name'); $rows = []; if ($r) while ($row = $r->fetch_assoc()) $rows[] = $row; return $rows; }
function setup_vehicle_types_find(mysqli $mysqli, int $id): ?array { $s = $mysqli->prepare('SELECT vehicle_type_id, vehicle_type_name FROM vehicle_type WHERE vehicle_type_id = ? LIMIT 1'); if (!$s) return null; $s->bind_param('i', $id); $s->execute(); $row = $s->get_result()->fetch_assoc(); $s->close(); return $row ?: null; }
function setup_vehicle_types_validate(array $d): array { $e = []; if (mb_strlen(trim((string) ($d['vehicle_type_name'] ?? ''))) < 2) $e[] = 'Vehicle type name is required.'; return $e; }
function setup_vehicle_types_name_exists(mysqli $mysqli, string $name, int $excludeId = 0): bool { $sql = 'SELECT vehicle_type_id FROM vehicle_type WHERE vehicle_type_name = ?'; if ($excludeId > 0) $sql .= ' AND vehicle_type_id <> ?'; $sql .= ' LIMIT 1'; $s = $mysqli->prepare($sql); if (!$s) return false; if ($excludeId > 0) $s->bind_param('si', $name, $excludeId); else $s->bind_param('s', $name); $s->execute(); $exists = (bool) $s->get_result()->fetch_assoc(); $s->close(); return $exists; }
function setup_vehicle_types_create(mysqli $mysqli, array $input): array { $d = ['vehicle_type_name' => trim((string) ($input['vehicle_type_name'] ?? ''))]; $e = setup_vehicle_types_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; if (setup_vehicle_types_name_exists($mysqli, $d['vehicle_type_name'])) return ['ok' => false, 'errors' => ['Vehicle type already exists.']]; $id = setup_vehicle_types_next_id($mysqli); $s = $mysqli->prepare('INSERT INTO vehicle_type (vehicle_type_id, vehicle_type_name) VALUES (?, ?)'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare insert.']]; $s->bind_param('is', $id, $d['vehicle_type_name']); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true, 'id' => $id] : ['ok' => false, 'errors' => ['Failed to create vehicle type.']]; }
function setup_vehicle_types_update(mysqli $mysqli, int $id, array $input): array { $d = ['vehicle_type_name' => trim((string) ($input['vehicle_type_name'] ?? ''))]; $e = setup_vehicle_types_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; if (setup_vehicle_types_name_exists($mysqli, $d['vehicle_type_name'], $id)) return ['ok' => false, 'errors' => ['Vehicle type already exists.']]; $s = $mysqli->prepare('UPDATE vehicle_type SET vehicle_type_name = ? WHERE vehicle_type_id = ?'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare update.']]; $s->bind_param('si', $d['vehicle_type_name'], $id); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true] : ['ok' => false, 'errors' => ['Failed to update vehicle type.']]; }
function setup_vehicle_types_delete(mysqli $mysqli, int $id): bool { $s = $mysqli->prepare('DELETE FROM vehicle_type WHERE vehicle_type_id = ?'); if (!$s) return false; $s->bind_param('i', $id); $ok = $s->execute(); $s->close(); return $ok; }

