<?php
declare(strict_types=1);

function setup_zones_flash_set(string $type, string $message): void { $_SESSION['setup_zones_flash'] = ['type' => $type, 'message' => $message]; }
function setup_zones_flash_get(): ?array { if (!isset($_SESSION['setup_zones_flash'])) return null; $f = $_SESSION['setup_zones_flash']; unset($_SESSION['setup_zones_flash']); return is_array($f) ? $f : null; }
function setup_zones_csrf_token(): string { if (empty($_SESSION['setup_zones_csrf'])) $_SESSION['setup_zones_csrf'] = bin2hex(random_bytes(16)); return (string) $_SESSION['setup_zones_csrf']; }
function setup_zones_csrf_validate(string $token): bool { $s = (string) ($_SESSION['setup_zones_csrf'] ?? ''); return $s !== '' && hash_equals($s, $token); }
function setup_zones_next_id(mysqli $mysqli): int { $r = $mysqli->query('SELECT COALESCE(MAX(zone_id),0)+1 AS n FROM zone'); if ($r && ($row = $r->fetch_assoc())) return max(1, (int) ($row['n'] ?? 1)); return 1; }
function setup_zones_locations(mysqli $mysqli): array { $r = $mysqli->query('SELECT location_name FROM location ORDER BY location_name'); $rows = []; if ($r) while ($row = $r->fetch_assoc()) { $n = trim((string) ($row['location_name'] ?? '')); if ($n !== '') $rows[] = $n; } return $rows; }
function setup_zones_list(mysqli $mysqli, ?string $location = null): array { $sql = 'SELECT zone_id, location_name, zone_name, zone_name_arabic FROM zone'; $types = ''; $params = []; if ($location !== null && $location !== '') { $sql .= ' WHERE location_name = ?'; $types = 's'; $params[] = $location; } $sql .= ' ORDER BY zone_name'; $s = $mysqli->prepare($sql); if (!$s) return []; if ($types !== '') $s->bind_param($types, ...$params); $s->execute(); $r = $s->get_result(); $rows = []; while ($row = $r->fetch_assoc()) $rows[] = $row; $s->close(); return $rows; }
function setup_zones_find(mysqli $mysqli, int $id): ?array { $s = $mysqli->prepare('SELECT zone_id, location_name, zone_name, zone_name_arabic FROM zone WHERE zone_id = ? LIMIT 1'); if (!$s) return null; $s->bind_param('i', $id); $s->execute(); $row = $s->get_result()->fetch_assoc(); $s->close(); return $row ?: null; }
function setup_zones_validate(array $d): array { $e = []; if (mb_strlen(trim((string) ($d['location_name'] ?? ''))) < 2) $e[] = 'Location is required.'; if (mb_strlen(trim((string) ($d['zone_name'] ?? ''))) < 2) $e[] = 'Zone name is required.'; if (mb_strlen(trim((string) ($d['zone_name_arabic'] ?? ''))) < 2) $e[] = 'Zone Arabic name is required.'; return $e; }
function setup_zones_create(mysqli $mysqli, array $input): array { $d = ['location_name' => trim((string) ($input['location_name'] ?? '')), 'zone_name' => trim((string) ($input['zone_name'] ?? '')), 'zone_name_arabic' => trim((string) ($input['zone_name_arabic'] ?? ''))]; $e = setup_zones_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; $id = setup_zones_next_id($mysqli); $locId = '0'; $s = $mysqli->prepare('INSERT INTO zone (zone_id, location_id, location_name, zone_name_arabic, zone_name) VALUES (?, ?, ?, ?, ?)'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare insert.']]; $s->bind_param('issss', $id, $locId, $d['location_name'], $d['zone_name_arabic'], $d['zone_name']); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true, 'id' => $id] : ['ok' => false, 'errors' => ['Failed to create zone.']]; }
function setup_zones_update(mysqli $mysqli, int $id, array $input): array { $d = ['location_name' => trim((string) ($input['location_name'] ?? '')), 'zone_name' => trim((string) ($input['zone_name'] ?? '')), 'zone_name_arabic' => trim((string) ($input['zone_name_arabic'] ?? ''))]; $e = setup_zones_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; $s = $mysqli->prepare('UPDATE zone SET location_name = ?, zone_name = ?, zone_name_arabic = ? WHERE zone_id = ?'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare update.']]; $s->bind_param('sssi', $d['location_name'], $d['zone_name'], $d['zone_name_arabic'], $id); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true] : ['ok' => false, 'errors' => ['Failed to update zone.']]; }
function setup_zones_delete(mysqli $mysqli, int $id): bool { $s = $mysqli->prepare('DELETE FROM zone WHERE zone_id = ?'); if (!$s) return false; $s->bind_param('i', $id); $ok = $s->execute(); $s->close(); return $ok; }

