<?php
declare(strict_types=1);

function setup_cities_flash_set(string $type, string $message): void { $_SESSION['setup_cities_flash'] = ['type' => $type, 'message' => $message]; }
function setup_cities_flash_get(): ?array { if (!isset($_SESSION['setup_cities_flash'])) return null; $f = $_SESSION['setup_cities_flash']; unset($_SESSION['setup_cities_flash']); return is_array($f) ? $f : null; }
function setup_cities_csrf_token(): string { if (empty($_SESSION['setup_cities_csrf'])) $_SESSION['setup_cities_csrf'] = bin2hex(random_bytes(16)); return (string) $_SESSION['setup_cities_csrf']; }
function setup_cities_csrf_validate(string $token): bool { $s = (string) ($_SESSION['setup_cities_csrf'] ?? ''); return $s !== '' && hash_equals($s, $token); }
function setup_cities_next_id(mysqli $mysqli): int { $r = $mysqli->query('SELECT COALESCE(MAX(city_id),0)+1 AS n FROM city'); if ($r && ($row = $r->fetch_assoc())) return max(1, (int) ($row['n'] ?? 1)); return 1; }
function setup_cities_countries(mysqli $mysqli): array { $r = $mysqli->query('SELECT country_name FROM country ORDER BY country_name'); $rows = []; if ($r) while ($row = $r->fetch_assoc()) { $n = trim((string) ($row['country_name'] ?? '')); if ($n !== '') $rows[] = $n; } return $rows; }
function setup_cities_list(mysqli $mysqli): array { $r = $mysqli->query('SELECT city_id, city_name, city_shotform, city_country_name FROM city ORDER BY city_name'); $rows = []; if ($r) while ($row = $r->fetch_assoc()) $rows[] = $row; return $rows; }
function setup_cities_find(mysqli $mysqli, int $id): ?array { $s = $mysqli->prepare('SELECT city_id, city_name, city_shotform, city_country_name FROM city WHERE city_id = ? LIMIT 1'); if (!$s) return null; $s->bind_param('i', $id); $s->execute(); $row = $s->get_result()->fetch_assoc(); $s->close(); return $row ?: null; }
function setup_cities_validate(array $d): array { $e = []; if (mb_strlen(trim((string) ($d['city_name'] ?? ''))) < 2) $e[] = 'City name is required.'; if (mb_strlen(trim((string) ($d['city_country_name'] ?? ''))) < 2) $e[] = 'Country is required.'; return $e; }
function setup_cities_create(mysqli $mysqli, array $input): array { $d = ['city_name' => trim((string) ($input['city_name'] ?? '')), 'city_shotform' => trim((string) ($input['city_shotform'] ?? '')), 'city_country_name' => trim((string) ($input['city_country_name'] ?? ''))]; $e = setup_cities_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; $id = setup_cities_next_id($mysqli); $s = $mysqli->prepare('INSERT INTO city (city_id, city_name, city_shotform, city_country_name) VALUES (?, ?, ?, ?)'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare insert.']]; $s->bind_param('isss', $id, $d['city_name'], $d['city_shotform'], $d['city_country_name']); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true, 'id' => $id] : ['ok' => false, 'errors' => ['Failed to create city.']]; }
function setup_cities_update(mysqli $mysqli, int $id, array $input): array { $d = ['city_name' => trim((string) ($input['city_name'] ?? '')), 'city_shotform' => trim((string) ($input['city_shotform'] ?? '')), 'city_country_name' => trim((string) ($input['city_country_name'] ?? ''))]; $e = setup_cities_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; $s = $mysqli->prepare('UPDATE city SET city_name = ?, city_shotform = ?, city_country_name = ? WHERE city_id = ?'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare update.']]; $s->bind_param('sssi', $d['city_name'], $d['city_shotform'], $d['city_country_name'], $id); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true] : ['ok' => false, 'errors' => ['Failed to update city.']]; }
function setup_cities_delete(mysqli $mysqli, int $id): bool { $s = $mysqli->prepare('DELETE FROM city WHERE city_id = ?'); if (!$s) return false; $s->bind_param('i', $id); $ok = $s->execute(); $s->close(); return $ok; }

