<?php
declare(strict_types=1);

function setup_departments_flash_set(string $type, string $message): void { $_SESSION['setup_departments_flash'] = ['type' => $type, 'message' => $message]; }
function setup_departments_flash_get(): ?array { if (!isset($_SESSION['setup_departments_flash'])) return null; $f = $_SESSION['setup_departments_flash']; unset($_SESSION['setup_departments_flash']); return is_array($f) ? $f : null; }
function setup_departments_csrf_token(): string { if (empty($_SESSION['setup_departments_csrf'])) $_SESSION['setup_departments_csrf'] = bin2hex(random_bytes(16)); return (string) $_SESSION['setup_departments_csrf']; }
function setup_departments_csrf_validate(string $token): bool { $s = (string) ($_SESSION['setup_departments_csrf'] ?? ''); return $s !== '' && hash_equals($s, $token); }
function setup_departments_next_id(mysqli $mysqli): int { $r = $mysqli->query('SELECT COALESCE(MAX(department_id),0)+1 AS n FROM department'); if ($r && ($row = $r->fetch_assoc())) return max(1, (int) ($row['n'] ?? 1)); return 1; }
function setup_departments_list(mysqli $mysqli): array { $r = $mysqli->query('SELECT department_id, department_name, department_name_short FROM department ORDER BY department_name'); $rows = []; if ($r) while ($row = $r->fetch_assoc()) $rows[] = $row; return $rows; }
function setup_departments_find(mysqli $mysqli, int $id): ?array { $s = $mysqli->prepare('SELECT department_id, department_name, department_name_short FROM department WHERE department_id = ? LIMIT 1'); if (!$s) return null; $s->bind_param('i', $id); $s->execute(); $row = $s->get_result()->fetch_assoc(); $s->close(); return $row ?: null; }
function setup_departments_validate(array $d): array { $e = []; if (mb_strlen(trim((string) ($d['department_name'] ?? ''))) < 2) $e[] = 'Department name is required.'; return $e; }
function setup_departments_name_exists(mysqli $mysqli, string $name, int $excludeId = 0): bool { $sql = 'SELECT department_id FROM department WHERE department_name = ?'; if ($excludeId > 0) $sql .= ' AND department_id <> ?'; $sql .= ' LIMIT 1'; $s = $mysqli->prepare($sql); if (!$s) return false; if ($excludeId > 0) $s->bind_param('si', $name, $excludeId); else $s->bind_param('s', $name); $s->execute(); $exists = (bool) $s->get_result()->fetch_assoc(); $s->close(); return $exists; }
function setup_departments_create(mysqli $mysqli, array $input): array { $d = ['department_name' => trim((string) ($input['department_name'] ?? '')), 'department_name_short' => trim((string) ($input['department_name_short'] ?? ''))]; $e = setup_departments_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; if (setup_departments_name_exists($mysqli, $d['department_name'])) return ['ok' => false, 'errors' => ['Department already exists.']]; $id = setup_departments_next_id($mysqli); $s = $mysqli->prepare('INSERT INTO department (department_id, department_name, department_name_short) VALUES (?, ?, ?)'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare insert.']]; $s->bind_param('iss', $id, $d['department_name'], $d['department_name_short']); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true, 'id' => $id] : ['ok' => false, 'errors' => ['Failed to create department.']]; }
function setup_departments_update(mysqli $mysqli, int $id, array $input): array { $d = ['department_name' => trim((string) ($input['department_name'] ?? '')), 'department_name_short' => trim((string) ($input['department_name_short'] ?? ''))]; $e = setup_departments_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; if (setup_departments_name_exists($mysqli, $d['department_name'], $id)) return ['ok' => false, 'errors' => ['Department already exists.']]; $s = $mysqli->prepare('UPDATE department SET department_name = ?, department_name_short = ? WHERE department_id = ?'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare update.']]; $s->bind_param('ssi', $d['department_name'], $d['department_name_short'], $id); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true] : ['ok' => false, 'errors' => ['Failed to update department.']]; }
function setup_departments_delete(mysqli $mysqli, int $id): bool { $s = $mysqli->prepare('DELETE FROM department WHERE department_id = ?'); if (!$s) return false; $s->bind_param('i', $id); $ok = $s->execute(); $s->close(); return $ok; }

