<?php
declare(strict_types=1);

function setup_countries_flash_set(string $type, string $message): void { $_SESSION['setup_countries_flash'] = ['type' => $type, 'message' => $message]; }
function setup_countries_flash_get(): ?array { if (!isset($_SESSION['setup_countries_flash'])) return null; $f = $_SESSION['setup_countries_flash']; unset($_SESSION['setup_countries_flash']); return is_array($f) ? $f : null; }
function setup_countries_csrf_token(): string { if (empty($_SESSION['setup_countries_csrf'])) $_SESSION['setup_countries_csrf'] = bin2hex(random_bytes(16)); return (string) $_SESSION['setup_countries_csrf']; }
function setup_countries_csrf_validate(string $token): bool { $s = (string) ($_SESSION['setup_countries_csrf'] ?? ''); return $s !== '' && hash_equals($s, $token); }
function setup_countries_next_id(mysqli $mysqli): int { $r = $mysqli->query('SELECT COALESCE(MAX(country_id),0)+1 AS n FROM country'); if ($r && ($row = $r->fetch_assoc())) return max(1, (int) ($row['n'] ?? 1)); return 1; }
function setup_countries_list(mysqli $mysqli): array { $r = $mysqli->query('SELECT country_id, country_name, country_shotform FROM country ORDER BY country_name'); $rows = []; if ($r) while ($row = $r->fetch_assoc()) $rows[] = $row; return $rows; }
function setup_countries_find(mysqli $mysqli, int $id): ?array { $s = $mysqli->prepare('SELECT country_id, country_name, country_shotform FROM country WHERE country_id = ? LIMIT 1'); if (!$s) return null; $s->bind_param('i', $id); $s->execute(); $row = $s->get_result()->fetch_assoc(); $s->close(); return $row ?: null; }
function setup_countries_validate(array $data): array { $e = []; if (mb_strlen(trim((string) ($data['country_name'] ?? ''))) < 2) $e[] = 'Country name is required.'; return $e; }
function setup_countries_name_exists(mysqli $mysqli, string $name, int $excludeId = 0): bool { $sql = 'SELECT country_id FROM country WHERE country_name = ?'; if ($excludeId > 0) $sql .= ' AND country_id <> ?'; $sql .= ' LIMIT 1'; $s = $mysqli->prepare($sql); if (!$s) return false; if ($excludeId > 0) $s->bind_param('si', $name, $excludeId); else $s->bind_param('s', $name); $s->execute(); $exists = (bool) $s->get_result()->fetch_assoc(); $s->close(); return $exists; }
function setup_countries_create(mysqli $mysqli, array $input): array { $d = ['country_name' => trim((string) ($input['country_name'] ?? '')), 'country_shotform' => trim((string) ($input['country_shotform'] ?? ''))]; $e = setup_countries_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; if (setup_countries_name_exists($mysqli, $d['country_name'])) return ['ok' => false, 'errors' => ['Country already exists.']]; $id = setup_countries_next_id($mysqli); $s = $mysqli->prepare('INSERT INTO country (country_id, country_name, country_shotform) VALUES (?, ?, ?)'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare insert.']]; $s->bind_param('iss', $id, $d['country_name'], $d['country_shotform']); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true, 'id' => $id] : ['ok' => false, 'errors' => ['Failed to create country.']]; }
function setup_countries_update(mysqli $mysqli, int $id, array $input): array { $d = ['country_name' => trim((string) ($input['country_name'] ?? '')), 'country_shotform' => trim((string) ($input['country_shotform'] ?? ''))]; $e = setup_countries_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; if (setup_countries_name_exists($mysqli, $d['country_name'], $id)) return ['ok' => false, 'errors' => ['Country already exists.']]; $s = $mysqli->prepare('UPDATE country SET country_name = ?, country_shotform = ? WHERE country_id = ?'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare update.']]; $s->bind_param('ssi', $d['country_name'], $d['country_shotform'], $id); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true] : ['ok' => false, 'errors' => ['Failed to update country.']]; }
function setup_countries_delete(mysqli $mysqli, int $id): bool { $s = $mysqli->prepare('DELETE FROM country WHERE country_id = ?'); if (!$s) return false; $s->bind_param('i', $id); $ok = $s->execute(); $s->close(); return $ok; }

