<?php
declare(strict_types=1);

function setup_sms_labels_flash_set(string $type, string $message): void { $_SESSION['setup_sms_labels_flash'] = ['type' => $type, 'message' => $message]; }
function setup_sms_labels_flash_get(): ?array { if (!isset($_SESSION['setup_sms_labels_flash'])) return null; $f = $_SESSION['setup_sms_labels_flash']; unset($_SESSION['setup_sms_labels_flash']); return is_array($f) ? $f : null; }
function setup_sms_labels_csrf_token(): string { if (empty($_SESSION['setup_sms_labels_csrf'])) $_SESSION['setup_sms_labels_csrf'] = bin2hex(random_bytes(16)); return (string) $_SESSION['setup_sms_labels_csrf']; }
function setup_sms_labels_csrf_validate(string $token): bool { $s = (string) ($_SESSION['setup_sms_labels_csrf'] ?? ''); return $s !== '' && hash_equals($s, $token); }
function setup_sms_labels_next_id(mysqli $mysqli): int { $r = $mysqli->query('SELECT COALESCE(MAX(sms_label_id),0)+1 AS n FROM sms_label'); if ($r && ($row = $r->fetch_assoc())) return max(1, (int) ($row['n'] ?? 1)); return 1; }
function setup_sms_labels_list(mysqli $mysqli): array { $r = $mysqli->query('SELECT sms_label_id, sms_label_header, sms_label_footer FROM sms_label ORDER BY sms_label_id DESC'); $rows = []; if ($r) while ($row = $r->fetch_assoc()) $rows[] = $row; return $rows; }
function setup_sms_labels_find(mysqli $mysqli, int $id): ?array { $s = $mysqli->prepare('SELECT sms_label_id, sms_label_header, sms_label_footer FROM sms_label WHERE sms_label_id = ? LIMIT 1'); if (!$s) return null; $s->bind_param('i', $id); $s->execute(); $row = $s->get_result()->fetch_assoc(); $s->close(); return $row ?: null; }
function setup_sms_labels_validate(array $d): array { $e = []; if (mb_strlen(trim((string) ($d['sms_label_header'] ?? ''))) < 2) $e[] = 'SMS header label is required.'; return $e; }
function setup_sms_labels_header_exists(mysqli $mysqli, string $header, int $excludeId = 0): bool { $sql = 'SELECT sms_label_id FROM sms_label WHERE sms_label_header = ?'; if ($excludeId > 0) $sql .= ' AND sms_label_id <> ?'; $sql .= ' LIMIT 1'; $s = $mysqli->prepare($sql); if (!$s) return false; if ($excludeId > 0) $s->bind_param('si', $header, $excludeId); else $s->bind_param('s', $header); $s->execute(); $exists = (bool) $s->get_result()->fetch_assoc(); $s->close(); return $exists; }
function setup_sms_labels_create(mysqli $mysqli, array $input): array { $d = ['sms_label_header' => trim((string) ($input['sms_label_header'] ?? '')), 'sms_label_footer' => trim((string) ($input['sms_label_footer'] ?? ''))]; $e = setup_sms_labels_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; if (setup_sms_labels_header_exists($mysqli, $d['sms_label_header'])) return ['ok' => false, 'errors' => ['Header already exists.']]; $id = setup_sms_labels_next_id($mysqli); $s = $mysqli->prepare('INSERT INTO sms_label (sms_label_id, sms_label_header, sms_label_footer) VALUES (?, ?, ?)'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare insert.']]; $s->bind_param('iss', $id, $d['sms_label_header'], $d['sms_label_footer']); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true, 'id' => $id] : ['ok' => false, 'errors' => ['Failed to create SMS label.']]; }
function setup_sms_labels_update(mysqli $mysqli, int $id, array $input): array { $d = ['sms_label_header' => trim((string) ($input['sms_label_header'] ?? '')), 'sms_label_footer' => trim((string) ($input['sms_label_footer'] ?? ''))]; $e = setup_sms_labels_validate($d); if ($e) return ['ok' => false, 'errors' => $e]; if (setup_sms_labels_header_exists($mysqli, $d['sms_label_header'], $id)) return ['ok' => false, 'errors' => ['Header already exists.']]; $s = $mysqli->prepare('UPDATE sms_label SET sms_label_header = ?, sms_label_footer = ? WHERE sms_label_id = ?'); if (!$s) return ['ok' => false, 'errors' => ['Failed to prepare update.']]; $s->bind_param('ssi', $d['sms_label_header'], $d['sms_label_footer'], $id); $ok = $s->execute(); $s->close(); return $ok ? ['ok' => true] : ['ok' => false, 'errors' => ['Failed to update SMS label.']]; }
function setup_sms_labels_delete(mysqli $mysqli, int $id): bool { $s = $mysqli->prepare('DELETE FROM sms_label WHERE sms_label_id = ?'); if (!$s) return false; $s->bind_param('i', $id); $ok = $s->execute(); $s->close(); return $ok; }

